[package]
name = "cookie-to-json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
iced = "0.5.2"
regex = "1.7.0"
